// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: build_processor_strategy.proto

#include "build_processor_strategy.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace open_vector_format {
        template <typename>
PROTOBUF_CONSTEXPR BuildProcessorStrategy_ParameterSet::BuildProcessorStrategy_ParameterSet(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.lpbf_meta_data_)*/ nullptr,
      /*decltype(_impl_.process_strategy_)*/ nullptr,
      /*decltype(_impl_.marking_params_)*/ nullptr,
    } {}
struct BuildProcessorStrategy_ParameterSetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BuildProcessorStrategy_ParameterSetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BuildProcessorStrategy_ParameterSetDefaultTypeInternal() {}
  union {
    BuildProcessorStrategy_ParameterSet _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BuildProcessorStrategy_ParameterSetDefaultTypeInternal _BuildProcessorStrategy_ParameterSet_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR BuildProcessorStrategy::BuildProcessorStrategy(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.parameter_sets_)*/ {},
      /*decltype(_impl_.build_processor_strategy_id_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.material_id_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.name_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.material_name_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct BuildProcessorStrategyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BuildProcessorStrategyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BuildProcessorStrategyDefaultTypeInternal() {}
  union {
    BuildProcessorStrategy _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BuildProcessorStrategyDefaultTypeInternal _BuildProcessorStrategy_default_instance_;
}  // namespace open_vector_format
static ::_pb::Metadata file_level_metadata_build_5fprocessor_5fstrategy_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_build_5fprocessor_5fstrategy_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_build_5fprocessor_5fstrategy_2eproto = nullptr;
const ::uint32_t TableStruct_build_5fprocessor_5fstrategy_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::open_vector_format::BuildProcessorStrategy_ParameterSet, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::open_vector_format::BuildProcessorStrategy_ParameterSet, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::open_vector_format::BuildProcessorStrategy_ParameterSet, _impl_.lpbf_meta_data_),
    PROTOBUF_FIELD_OFFSET(::open_vector_format::BuildProcessorStrategy_ParameterSet, _impl_.process_strategy_),
    PROTOBUF_FIELD_OFFSET(::open_vector_format::BuildProcessorStrategy_ParameterSet, _impl_.marking_params_),
    0,
    1,
    2,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::open_vector_format::BuildProcessorStrategy, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::open_vector_format::BuildProcessorStrategy, _impl_.build_processor_strategy_id_),
    PROTOBUF_FIELD_OFFSET(::open_vector_format::BuildProcessorStrategy, _impl_.material_id_),
    PROTOBUF_FIELD_OFFSET(::open_vector_format::BuildProcessorStrategy, _impl_.name_),
    PROTOBUF_FIELD_OFFSET(::open_vector_format::BuildProcessorStrategy, _impl_.material_name_),
    PROTOBUF_FIELD_OFFSET(::open_vector_format::BuildProcessorStrategy, _impl_.parameter_sets_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::open_vector_format::BuildProcessorStrategy_ParameterSet)},
        {14, -1, -1, sizeof(::open_vector_format::BuildProcessorStrategy)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::open_vector_format::_BuildProcessorStrategy_ParameterSet_default_instance_._instance,
    &::open_vector_format::_BuildProcessorStrategy_default_instance_._instance,
};
const char descriptor_table_protodef_build_5fprocessor_5fstrategy_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\036build_processor_strategy.proto\022\022open_v"
    "ector_format\032\030open_vector_format.proto\"\236"
    "\003\n\026BuildProcessorStrategy\022#\n\033build_proce"
    "ssor_strategy_id\030\001 \001(\t\022\023\n\013material_id\030\002 "
    "\001(\t\022\014\n\004name\030\003 \001(\t\022\025\n\rmaterial_name\030\004 \001(\t"
    "\022O\n\016parameter_sets\030\005 \003(\01327.open_vector_f"
    "ormat.BuildProcessorStrategy.ParameterSe"
    "t\032\323\001\n\014ParameterSet\022D\n\016lpbf_meta_data\030\001 \001"
    "(\0132,.open_vector_format.VectorBlock.LPBF"
    "Metadata\022B\n\020process_strategy\030\002 \001(\0132(.ope"
    "n_vector_format.Part.ProcessStrategy\0229\n\016"
    "marking_params\030\003 \001(\0132!.open_vector_forma"
    "t.MarkingParamsB=Z;github.com/digital-pr"
    "oduction-aachen/openvectorformat/protob\006"
    "proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_build_5fprocessor_5fstrategy_2eproto_deps[1] =
    {
        &::descriptor_table_open_5fvector_5fformat_2eproto,
};
static ::absl::once_flag descriptor_table_build_5fprocessor_5fstrategy_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_build_5fprocessor_5fstrategy_2eproto = {
    false,
    false,
    566,
    descriptor_table_protodef_build_5fprocessor_5fstrategy_2eproto,
    "build_processor_strategy.proto",
    &descriptor_table_build_5fprocessor_5fstrategy_2eproto_once,
    descriptor_table_build_5fprocessor_5fstrategy_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_build_5fprocessor_5fstrategy_2eproto::offsets,
    file_level_metadata_build_5fprocessor_5fstrategy_2eproto,
    file_level_enum_descriptors_build_5fprocessor_5fstrategy_2eproto,
    file_level_service_descriptors_build_5fprocessor_5fstrategy_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_build_5fprocessor_5fstrategy_2eproto_getter() {
  return &descriptor_table_build_5fprocessor_5fstrategy_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_build_5fprocessor_5fstrategy_2eproto(&descriptor_table_build_5fprocessor_5fstrategy_2eproto);
namespace open_vector_format {
// ===================================================================

class BuildProcessorStrategy_ParameterSet::_Internal {
 public:
  using HasBits = decltype(std::declval<BuildProcessorStrategy_ParameterSet>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy_ParameterSet, _impl_._has_bits_);
  static const ::open_vector_format::VectorBlock_LPBFMetadata& lpbf_meta_data(const BuildProcessorStrategy_ParameterSet* msg);
  static void set_has_lpbf_meta_data(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::open_vector_format::Part_ProcessStrategy& process_strategy(const BuildProcessorStrategy_ParameterSet* msg);
  static void set_has_process_strategy(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::open_vector_format::MarkingParams& marking_params(const BuildProcessorStrategy_ParameterSet* msg);
  static void set_has_marking_params(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

const ::open_vector_format::VectorBlock_LPBFMetadata& BuildProcessorStrategy_ParameterSet::_Internal::lpbf_meta_data(const BuildProcessorStrategy_ParameterSet* msg) {
  return *msg->_impl_.lpbf_meta_data_;
}
const ::open_vector_format::Part_ProcessStrategy& BuildProcessorStrategy_ParameterSet::_Internal::process_strategy(const BuildProcessorStrategy_ParameterSet* msg) {
  return *msg->_impl_.process_strategy_;
}
const ::open_vector_format::MarkingParams& BuildProcessorStrategy_ParameterSet::_Internal::marking_params(const BuildProcessorStrategy_ParameterSet* msg) {
  return *msg->_impl_.marking_params_;
}
void BuildProcessorStrategy_ParameterSet::clear_lpbf_meta_data() {
  if (_impl_.lpbf_meta_data_ != nullptr) _impl_.lpbf_meta_data_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void BuildProcessorStrategy_ParameterSet::clear_process_strategy() {
  if (_impl_.process_strategy_ != nullptr) _impl_.process_strategy_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
void BuildProcessorStrategy_ParameterSet::clear_marking_params() {
  if (_impl_.marking_params_ != nullptr) _impl_.marking_params_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
BuildProcessorStrategy_ParameterSet::BuildProcessorStrategy_ParameterSet(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:open_vector_format.BuildProcessorStrategy.ParameterSet)
}
BuildProcessorStrategy_ParameterSet::BuildProcessorStrategy_ParameterSet(const BuildProcessorStrategy_ParameterSet& from) : ::google::protobuf::Message() {
  BuildProcessorStrategy_ParameterSet* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.lpbf_meta_data_){nullptr},
      decltype(_impl_.process_strategy_){nullptr},
      decltype(_impl_.marking_params_){nullptr},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.lpbf_meta_data_ = new ::open_vector_format::VectorBlock_LPBFMetadata(*from._impl_.lpbf_meta_data_);
  }
  if ((from._impl_._has_bits_[0] & 0x00000002u) != 0) {
    _this->_impl_.process_strategy_ = new ::open_vector_format::Part_ProcessStrategy(*from._impl_.process_strategy_);
  }
  if ((from._impl_._has_bits_[0] & 0x00000004u) != 0) {
    _this->_impl_.marking_params_ = new ::open_vector_format::MarkingParams(*from._impl_.marking_params_);
  }

  // @@protoc_insertion_point(copy_constructor:open_vector_format.BuildProcessorStrategy.ParameterSet)
}
inline void BuildProcessorStrategy_ParameterSet::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.lpbf_meta_data_){nullptr},
      decltype(_impl_.process_strategy_){nullptr},
      decltype(_impl_.marking_params_){nullptr},
  };
}
BuildProcessorStrategy_ParameterSet::~BuildProcessorStrategy_ParameterSet() {
  // @@protoc_insertion_point(destructor:open_vector_format.BuildProcessorStrategy.ParameterSet)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void BuildProcessorStrategy_ParameterSet::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.lpbf_meta_data_;
  if (this != internal_default_instance()) delete _impl_.process_strategy_;
  if (this != internal_default_instance()) delete _impl_.marking_params_;
}
void BuildProcessorStrategy_ParameterSet::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void BuildProcessorStrategy_ParameterSet::Clear() {
// @@protoc_insertion_point(message_clear_start:open_vector_format.BuildProcessorStrategy.ParameterSet)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.lpbf_meta_data_ != nullptr);
      _impl_.lpbf_meta_data_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.process_strategy_ != nullptr);
      _impl_.process_strategy_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.marking_params_ != nullptr);
      _impl_.marking_params_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* BuildProcessorStrategy_ParameterSet::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 3, 0, 2> BuildProcessorStrategy_ParameterSet::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy_ParameterSet, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_BuildProcessorStrategy_ParameterSet_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .open_vector_format.VectorBlock.LPBFMetadata lpbf_meta_data = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy_ParameterSet, _impl_.lpbf_meta_data_)}},
    // .open_vector_format.Part.ProcessStrategy process_strategy = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy_ParameterSet, _impl_.process_strategy_)}},
    // .open_vector_format.MarkingParams marking_params = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 2, PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy_ParameterSet, _impl_.marking_params_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .open_vector_format.VectorBlock.LPBFMetadata lpbf_meta_data = 1;
    {PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy_ParameterSet, _impl_.lpbf_meta_data_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .open_vector_format.Part.ProcessStrategy process_strategy = 2;
    {PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy_ParameterSet, _impl_.process_strategy_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .open_vector_format.MarkingParams marking_params = 3;
    {PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy_ParameterSet, _impl_.marking_params_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::open_vector_format::VectorBlock_LPBFMetadata>()},
    {::_pbi::TcParser::GetTable<::open_vector_format::Part_ProcessStrategy>()},
    {::_pbi::TcParser::GetTable<::open_vector_format::MarkingParams>()},
  }}, {{
  }},
};

::uint8_t* BuildProcessorStrategy_ParameterSet::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:open_vector_format.BuildProcessorStrategy.ParameterSet)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .open_vector_format.VectorBlock.LPBFMetadata lpbf_meta_data = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::lpbf_meta_data(this),
        _Internal::lpbf_meta_data(this).GetCachedSize(), target, stream);
  }

  // .open_vector_format.Part.ProcessStrategy process_strategy = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::process_strategy(this),
        _Internal::process_strategy(this).GetCachedSize(), target, stream);
  }

  // .open_vector_format.MarkingParams marking_params = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::marking_params(this),
        _Internal::marking_params(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:open_vector_format.BuildProcessorStrategy.ParameterSet)
  return target;
}

::size_t BuildProcessorStrategy_ParameterSet::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:open_vector_format.BuildProcessorStrategy.ParameterSet)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // .open_vector_format.VectorBlock.LPBFMetadata lpbf_meta_data = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *_impl_.lpbf_meta_data_);
    }

    // .open_vector_format.Part.ProcessStrategy process_strategy = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *_impl_.process_strategy_);
    }

    // .open_vector_format.MarkingParams marking_params = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *_impl_.marking_params_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData BuildProcessorStrategy_ParameterSet::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    BuildProcessorStrategy_ParameterSet::MergeImpl
};
const ::google::protobuf::Message::ClassData*BuildProcessorStrategy_ParameterSet::GetClassData() const { return &_class_data_; }


void BuildProcessorStrategy_ParameterSet::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<BuildProcessorStrategy_ParameterSet*>(&to_msg);
  auto& from = static_cast<const BuildProcessorStrategy_ParameterSet&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:open_vector_format.BuildProcessorStrategy.ParameterSet)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_lpbf_meta_data()->::open_vector_format::VectorBlock_LPBFMetadata::MergeFrom(
          from._internal_lpbf_meta_data());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_process_strategy()->::open_vector_format::Part_ProcessStrategy::MergeFrom(
          from._internal_process_strategy());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_mutable_marking_params()->::open_vector_format::MarkingParams::MergeFrom(
          from._internal_marking_params());
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BuildProcessorStrategy_ParameterSet::CopyFrom(const BuildProcessorStrategy_ParameterSet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:open_vector_format.BuildProcessorStrategy.ParameterSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool BuildProcessorStrategy_ParameterSet::IsInitialized() const {
  return true;
}

void BuildProcessorStrategy_ParameterSet::InternalSwap(BuildProcessorStrategy_ParameterSet* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy_ParameterSet, _impl_.marking_params_)
      + sizeof(BuildProcessorStrategy_ParameterSet::_impl_.marking_params_)
      - PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy_ParameterSet, _impl_.lpbf_meta_data_)>(
          reinterpret_cast<char*>(&_impl_.lpbf_meta_data_),
          reinterpret_cast<char*>(&other->_impl_.lpbf_meta_data_));
}

::google::protobuf::Metadata BuildProcessorStrategy_ParameterSet::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_build_5fprocessor_5fstrategy_2eproto_getter, &descriptor_table_build_5fprocessor_5fstrategy_2eproto_once,
      file_level_metadata_build_5fprocessor_5fstrategy_2eproto[0]);
}
// ===================================================================

class BuildProcessorStrategy::_Internal {
 public:
};

BuildProcessorStrategy::BuildProcessorStrategy(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:open_vector_format.BuildProcessorStrategy)
}
BuildProcessorStrategy::BuildProcessorStrategy(const BuildProcessorStrategy& from) : ::google::protobuf::Message() {
  BuildProcessorStrategy* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.parameter_sets_){from._impl_.parameter_sets_},
      decltype(_impl_.build_processor_strategy_id_){},
      decltype(_impl_.material_id_){},
      decltype(_impl_.name_){},
      decltype(_impl_.material_name_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _impl_.build_processor_strategy_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.build_processor_strategy_id_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_build_processor_strategy_id().empty()) {
    _this->_impl_.build_processor_strategy_id_.Set(from._internal_build_processor_strategy_id(), _this->GetArenaForAllocation());
  }
  _impl_.material_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.material_id_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_material_id().empty()) {
    _this->_impl_.material_id_.Set(from._internal_material_id(), _this->GetArenaForAllocation());
  }
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), _this->GetArenaForAllocation());
  }
  _impl_.material_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.material_name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_material_name().empty()) {
    _this->_impl_.material_name_.Set(from._internal_material_name(), _this->GetArenaForAllocation());
  }

  // @@protoc_insertion_point(copy_constructor:open_vector_format.BuildProcessorStrategy)
}
inline void BuildProcessorStrategy::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.parameter_sets_){arena},
      decltype(_impl_.build_processor_strategy_id_){},
      decltype(_impl_.material_id_){},
      decltype(_impl_.name_){},
      decltype(_impl_.material_name_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _impl_.build_processor_strategy_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.build_processor_strategy_id_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.material_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.material_id_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.material_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.material_name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
BuildProcessorStrategy::~BuildProcessorStrategy() {
  // @@protoc_insertion_point(destructor:open_vector_format.BuildProcessorStrategy)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void BuildProcessorStrategy::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.parameter_sets_.~RepeatedPtrField();
  _impl_.build_processor_strategy_id_.Destroy();
  _impl_.material_id_.Destroy();
  _impl_.name_.Destroy();
  _impl_.material_name_.Destroy();
}
void BuildProcessorStrategy::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void BuildProcessorStrategy::Clear() {
// @@protoc_insertion_point(message_clear_start:open_vector_format.BuildProcessorStrategy)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_parameter_sets()->Clear();
  _impl_.build_processor_strategy_id_.ClearToEmpty();
  _impl_.material_id_.ClearToEmpty();
  _impl_.name_.ClearToEmpty();
  _impl_.material_name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* BuildProcessorStrategy::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 1, 105, 2> BuildProcessorStrategy::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_BuildProcessorStrategy_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string build_processor_strategy_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy, _impl_.build_processor_strategy_id_)}},
    // string material_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy, _impl_.material_id_)}},
    // string name = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy, _impl_.name_)}},
    // string material_name = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy, _impl_.material_name_)}},
    // repeated .open_vector_format.BuildProcessorStrategy.ParameterSet parameter_sets = 5;
    {::_pbi::TcParser::FastMtR1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy, _impl_.parameter_sets_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string build_processor_strategy_id = 1;
    {PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy, _impl_.build_processor_strategy_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string material_id = 2;
    {PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy, _impl_.material_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string name = 3;
    {PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string material_name = 4;
    {PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy, _impl_.material_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .open_vector_format.BuildProcessorStrategy.ParameterSet parameter_sets = 5;
    {PROTOBUF_FIELD_OFFSET(BuildProcessorStrategy, _impl_.parameter_sets_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::open_vector_format::BuildProcessorStrategy_ParameterSet>()},
  }}, {{
    "\51\33\13\4\15\0\0\0"
    "open_vector_format.BuildProcessorStrategy"
    "build_processor_strategy_id"
    "material_id"
    "name"
    "material_name"
  }},
};

::uint8_t* BuildProcessorStrategy::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:open_vector_format.BuildProcessorStrategy)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string build_processor_strategy_id = 1;
  if (!this->_internal_build_processor_strategy_id().empty()) {
    const std::string& _s = this->_internal_build_processor_strategy_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "open_vector_format.BuildProcessorStrategy.build_processor_strategy_id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string material_id = 2;
  if (!this->_internal_material_id().empty()) {
    const std::string& _s = this->_internal_material_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "open_vector_format.BuildProcessorStrategy.material_id");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string name = 3;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "open_vector_format.BuildProcessorStrategy.name");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string material_name = 4;
  if (!this->_internal_material_name().empty()) {
    const std::string& _s = this->_internal_material_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "open_vector_format.BuildProcessorStrategy.material_name");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // repeated .open_vector_format.BuildProcessorStrategy.ParameterSet parameter_sets = 5;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_parameter_sets_size()); i < n; i++) {
    const auto& repfield = this->_internal_parameter_sets().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(5, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:open_vector_format.BuildProcessorStrategy)
  return target;
}

::size_t BuildProcessorStrategy::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:open_vector_format.BuildProcessorStrategy)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .open_vector_format.BuildProcessorStrategy.ParameterSet parameter_sets = 5;
  total_size += 1UL * this->_internal_parameter_sets_size();
  for (const auto& msg : this->_internal_parameter_sets()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // string build_processor_strategy_id = 1;
  if (!this->_internal_build_processor_strategy_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_build_processor_strategy_id());
  }

  // string material_id = 2;
  if (!this->_internal_material_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_material_id());
  }

  // string name = 3;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // string material_name = 4;
  if (!this->_internal_material_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_material_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData BuildProcessorStrategy::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    BuildProcessorStrategy::MergeImpl
};
const ::google::protobuf::Message::ClassData*BuildProcessorStrategy::GetClassData() const { return &_class_data_; }


void BuildProcessorStrategy::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<BuildProcessorStrategy*>(&to_msg);
  auto& from = static_cast<const BuildProcessorStrategy&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:open_vector_format.BuildProcessorStrategy)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_parameter_sets()->MergeFrom(from._internal_parameter_sets());
  if (!from._internal_build_processor_strategy_id().empty()) {
    _this->_internal_set_build_processor_strategy_id(from._internal_build_processor_strategy_id());
  }
  if (!from._internal_material_id().empty()) {
    _this->_internal_set_material_id(from._internal_material_id());
  }
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_material_name().empty()) {
    _this->_internal_set_material_name(from._internal_material_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BuildProcessorStrategy::CopyFrom(const BuildProcessorStrategy& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:open_vector_format.BuildProcessorStrategy)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool BuildProcessorStrategy::IsInitialized() const {
  return true;
}

void BuildProcessorStrategy::InternalSwap(BuildProcessorStrategy* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.parameter_sets_.InternalSwap(&other->_impl_.parameter_sets_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.build_processor_strategy_id_, lhs_arena,
                                       &other->_impl_.build_processor_strategy_id_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.material_id_, lhs_arena,
                                       &other->_impl_.material_id_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, lhs_arena,
                                       &other->_impl_.name_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.material_name_, lhs_arena,
                                       &other->_impl_.material_name_, rhs_arena);
}

::google::protobuf::Metadata BuildProcessorStrategy::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_build_5fprocessor_5fstrategy_2eproto_getter, &descriptor_table_build_5fprocessor_5fstrategy_2eproto_once,
      file_level_metadata_build_5fprocessor_5fstrategy_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace open_vector_format
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
