# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: build_processor_strategy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import open_vector_format_pb2 as open__vector__format__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x62uild_processor_strategy.proto\x12\x12open_vector_format\x1a\x18open_vector_format.proto\"\x9e\x03\n\x16\x42uildProcessorStrategy\x12#\n\x1b\x62uild_processor_strategy_id\x18\x01 \x01(\t\x12\x13\n\x0bmaterial_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x15\n\rmaterial_name\x18\x04 \x01(\t\x12O\n\x0eparameter_sets\x18\x05 \x03(\x0b\x32\x37.open_vector_format.BuildProcessorStrategy.ParameterSet\x1a\xd3\x01\n\x0cParameterSet\x12\x44\n\x0elpbf_meta_data\x18\x01 \x01(\x0b\x32,.open_vector_format.VectorBlock.LPBFMetadata\x12\x42\n\x10process_strategy\x18\x02 \x01(\x0b\x32(.open_vector_format.Part.ProcessStrategy\x12\x39\n\x0emarking_params\x18\x03 \x01(\x0b\x32!.open_vector_format.MarkingParamsB=Z;github.com/digital-production-aachen/openvectorformat/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'build_processor_strategy_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z;github.com/digital-production-aachen/openvectorformat/proto'
  _globals['_BUILDPROCESSORSTRATEGY']._serialized_start=81
  _globals['_BUILDPROCESSORSTRATEGY']._serialized_end=495
  _globals['_BUILDPROCESSORSTRATEGY_PARAMETERSET']._serialized_start=284
  _globals['_BUILDPROCESSORSTRATEGY_PARAMETERSET']._serialized_end=495
# @@protoc_insertion_point(module_scope)
