// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: build_processor_strategy.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OpenVectorFormat {

  /// <summary>Holder for reflection information generated from build_processor_strategy.proto</summary>
  public static partial class BuildProcessorStrategyReflection {

    #region Descriptor
    /// <summary>File descriptor for build_processor_strategy.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BuildProcessorStrategyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5idWlsZF9wcm9jZXNzb3Jfc3RyYXRlZ3kucHJvdG8SEm9wZW5fdmVjdG9y",
            "X2Zvcm1hdBoYb3Blbl92ZWN0b3JfZm9ybWF0LnByb3RvIp4DChZCdWlsZFBy",
            "b2Nlc3NvclN0cmF0ZWd5EiMKG2J1aWxkX3Byb2Nlc3Nvcl9zdHJhdGVneV9p",
            "ZBgBIAEoCRITCgttYXRlcmlhbF9pZBgCIAEoCRIMCgRuYW1lGAMgASgJEhUK",
            "DW1hdGVyaWFsX25hbWUYBCABKAkSTwoOcGFyYW1ldGVyX3NldHMYBSADKAsy",
            "Ny5vcGVuX3ZlY3Rvcl9mb3JtYXQuQnVpbGRQcm9jZXNzb3JTdHJhdGVneS5Q",
            "YXJhbWV0ZXJTZXQa0wEKDFBhcmFtZXRlclNldBJECg5scGJmX21ldGFfZGF0",
            "YRgBIAEoCzIsLm9wZW5fdmVjdG9yX2Zvcm1hdC5WZWN0b3JCbG9jay5MUEJG",
            "TWV0YWRhdGESQgoQcHJvY2Vzc19zdHJhdGVneRgCIAEoCzIoLm9wZW5fdmVj",
            "dG9yX2Zvcm1hdC5QYXJ0LlByb2Nlc3NTdHJhdGVneRI5Cg5tYXJraW5nX3Bh",
            "cmFtcxgDIAEoCzIhLm9wZW5fdmVjdG9yX2Zvcm1hdC5NYXJraW5nUGFyYW1z",
            "Qj1aO2dpdGh1Yi5jb20vZGlnaXRhbC1wcm9kdWN0aW9uLWFhY2hlbi9vcGVu",
            "dmVjdG9yZm9ybWF0L3Byb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::OpenVectorFormat.OpenVectorFormatReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenVectorFormat.BuildProcessorStrategy), global::OpenVectorFormat.BuildProcessorStrategy.Parser, new[]{ "BuildProcessorStrategyId", "MaterialId", "Name", "MaterialName", "ParameterSets" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::OpenVectorFormat.BuildProcessorStrategy.Types.ParameterSet), global::OpenVectorFormat.BuildProcessorStrategy.Types.ParameterSet.Parser, new[]{ "LpbfMetaData", "ProcessStrategy", "MarkingParams" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///BuildProcessorStrategy is a settings collection object for a build processor.
  ///This definition uses OpenVectorFormat definitions to save a collection of settings
  ///for a specific material that can be used to add parameters to OVF vector data
  ///based on the LPBF meta data of VectorBlock objects.
  ///For each meta data combination a process strategy and marking params can be stored.
  ///Handling parameter fallbacks is responsibility of the build processor.
  /// </summary>
  public sealed partial class BuildProcessorStrategy : pb::IMessage<BuildProcessorStrategy>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BuildProcessorStrategy> _parser = new pb::MessageParser<BuildProcessorStrategy>(() => new BuildProcessorStrategy());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BuildProcessorStrategy> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenVectorFormat.BuildProcessorStrategyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BuildProcessorStrategy() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BuildProcessorStrategy(BuildProcessorStrategy other) : this() {
      buildProcessorStrategyId_ = other.buildProcessorStrategyId_;
      materialId_ = other.materialId_;
      name_ = other.name_;
      materialName_ = other.materialName_;
      parameterSets_ = other.parameterSets_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BuildProcessorStrategy Clone() {
      return new BuildProcessorStrategy(this);
    }

    /// <summary>Field number for the "build_processor_strategy_id" field.</summary>
    public const int BuildProcessorStrategyIdFieldNumber = 1;
    private string buildProcessorStrategyId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BuildProcessorStrategyId {
      get { return buildProcessorStrategyId_; }
      set {
        buildProcessorStrategyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "material_id" field.</summary>
    public const int MaterialIdFieldNumber = 2;
    private string materialId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MaterialId {
      get { return materialId_; }
      set {
        materialId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "material_name" field.</summary>
    public const int MaterialNameFieldNumber = 4;
    private string materialName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MaterialName {
      get { return materialName_; }
      set {
        materialName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "parameter_sets" field.</summary>
    public const int ParameterSetsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::OpenVectorFormat.BuildProcessorStrategy.Types.ParameterSet> _repeated_parameterSets_codec
        = pb::FieldCodec.ForMessage(42, global::OpenVectorFormat.BuildProcessorStrategy.Types.ParameterSet.Parser);
    private readonly pbc::RepeatedField<global::OpenVectorFormat.BuildProcessorStrategy.Types.ParameterSet> parameterSets_ = new pbc::RepeatedField<global::OpenVectorFormat.BuildProcessorStrategy.Types.ParameterSet>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::OpenVectorFormat.BuildProcessorStrategy.Types.ParameterSet> ParameterSets {
      get { return parameterSets_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BuildProcessorStrategy);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BuildProcessorStrategy other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BuildProcessorStrategyId != other.BuildProcessorStrategyId) return false;
      if (MaterialId != other.MaterialId) return false;
      if (Name != other.Name) return false;
      if (MaterialName != other.MaterialName) return false;
      if(!parameterSets_.Equals(other.parameterSets_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BuildProcessorStrategyId.Length != 0) hash ^= BuildProcessorStrategyId.GetHashCode();
      if (MaterialId.Length != 0) hash ^= MaterialId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (MaterialName.Length != 0) hash ^= MaterialName.GetHashCode();
      hash ^= parameterSets_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BuildProcessorStrategyId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(BuildProcessorStrategyId);
      }
      if (MaterialId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MaterialId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (MaterialName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(MaterialName);
      }
      parameterSets_.WriteTo(output, _repeated_parameterSets_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BuildProcessorStrategyId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(BuildProcessorStrategyId);
      }
      if (MaterialId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MaterialId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (MaterialName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(MaterialName);
      }
      parameterSets_.WriteTo(ref output, _repeated_parameterSets_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BuildProcessorStrategyId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BuildProcessorStrategyId);
      }
      if (MaterialId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MaterialId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (MaterialName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MaterialName);
      }
      size += parameterSets_.CalculateSize(_repeated_parameterSets_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BuildProcessorStrategy other) {
      if (other == null) {
        return;
      }
      if (other.BuildProcessorStrategyId.Length != 0) {
        BuildProcessorStrategyId = other.BuildProcessorStrategyId;
      }
      if (other.MaterialId.Length != 0) {
        MaterialId = other.MaterialId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.MaterialName.Length != 0) {
        MaterialName = other.MaterialName;
      }
      parameterSets_.Add(other.parameterSets_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            BuildProcessorStrategyId = input.ReadString();
            break;
          }
          case 18: {
            MaterialId = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            MaterialName = input.ReadString();
            break;
          }
          case 42: {
            parameterSets_.AddEntriesFrom(input, _repeated_parameterSets_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            BuildProcessorStrategyId = input.ReadString();
            break;
          }
          case 18: {
            MaterialId = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            MaterialName = input.ReadString();
            break;
          }
          case 42: {
            parameterSets_.AddEntriesFrom(ref input, _repeated_parameterSets_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the BuildProcessorStrategy message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class ParameterSet : pb::IMessage<ParameterSet>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ParameterSet> _parser = new pb::MessageParser<ParameterSet>(() => new ParameterSet());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ParameterSet> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::OpenVectorFormat.BuildProcessorStrategy.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ParameterSet() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ParameterSet(ParameterSet other) : this() {
          lpbfMetaData_ = other.lpbfMetaData_ != null ? other.lpbfMetaData_.Clone() : null;
          processStrategy_ = other.processStrategy_ != null ? other.processStrategy_.Clone() : null;
          markingParams_ = other.markingParams_ != null ? other.markingParams_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ParameterSet Clone() {
          return new ParameterSet(this);
        }

        /// <summary>Field number for the "lpbf_meta_data" field.</summary>
        public const int LpbfMetaDataFieldNumber = 1;
        private global::OpenVectorFormat.VectorBlock.Types.LPBFMetadata lpbfMetaData_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::OpenVectorFormat.VectorBlock.Types.LPBFMetadata LpbfMetaData {
          get { return lpbfMetaData_; }
          set {
            lpbfMetaData_ = value;
          }
        }

        /// <summary>Field number for the "process_strategy" field.</summary>
        public const int ProcessStrategyFieldNumber = 2;
        private global::OpenVectorFormat.Part.Types.ProcessStrategy processStrategy_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::OpenVectorFormat.Part.Types.ProcessStrategy ProcessStrategy {
          get { return processStrategy_; }
          set {
            processStrategy_ = value;
          }
        }

        /// <summary>Field number for the "marking_params" field.</summary>
        public const int MarkingParamsFieldNumber = 3;
        private global::OpenVectorFormat.MarkingParams markingParams_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::OpenVectorFormat.MarkingParams MarkingParams {
          get { return markingParams_; }
          set {
            markingParams_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as ParameterSet);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ParameterSet other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(LpbfMetaData, other.LpbfMetaData)) return false;
          if (!object.Equals(ProcessStrategy, other.ProcessStrategy)) return false;
          if (!object.Equals(MarkingParams, other.MarkingParams)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (lpbfMetaData_ != null) hash ^= LpbfMetaData.GetHashCode();
          if (processStrategy_ != null) hash ^= ProcessStrategy.GetHashCode();
          if (markingParams_ != null) hash ^= MarkingParams.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (lpbfMetaData_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(LpbfMetaData);
          }
          if (processStrategy_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(ProcessStrategy);
          }
          if (markingParams_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(MarkingParams);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (lpbfMetaData_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(LpbfMetaData);
          }
          if (processStrategy_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(ProcessStrategy);
          }
          if (markingParams_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(MarkingParams);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (lpbfMetaData_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(LpbfMetaData);
          }
          if (processStrategy_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(ProcessStrategy);
          }
          if (markingParams_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(MarkingParams);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ParameterSet other) {
          if (other == null) {
            return;
          }
          if (other.lpbfMetaData_ != null) {
            if (lpbfMetaData_ == null) {
              LpbfMetaData = new global::OpenVectorFormat.VectorBlock.Types.LPBFMetadata();
            }
            LpbfMetaData.MergeFrom(other.LpbfMetaData);
          }
          if (other.processStrategy_ != null) {
            if (processStrategy_ == null) {
              ProcessStrategy = new global::OpenVectorFormat.Part.Types.ProcessStrategy();
            }
            ProcessStrategy.MergeFrom(other.ProcessStrategy);
          }
          if (other.markingParams_ != null) {
            if (markingParams_ == null) {
              MarkingParams = new global::OpenVectorFormat.MarkingParams();
            }
            MarkingParams.MergeFrom(other.MarkingParams);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (lpbfMetaData_ == null) {
                  LpbfMetaData = new global::OpenVectorFormat.VectorBlock.Types.LPBFMetadata();
                }
                input.ReadMessage(LpbfMetaData);
                break;
              }
              case 18: {
                if (processStrategy_ == null) {
                  ProcessStrategy = new global::OpenVectorFormat.Part.Types.ProcessStrategy();
                }
                input.ReadMessage(ProcessStrategy);
                break;
              }
              case 26: {
                if (markingParams_ == null) {
                  MarkingParams = new global::OpenVectorFormat.MarkingParams();
                }
                input.ReadMessage(MarkingParams);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                if (lpbfMetaData_ == null) {
                  LpbfMetaData = new global::OpenVectorFormat.VectorBlock.Types.LPBFMetadata();
                }
                input.ReadMessage(LpbfMetaData);
                break;
              }
              case 18: {
                if (processStrategy_ == null) {
                  ProcessStrategy = new global::OpenVectorFormat.Part.Types.ProcessStrategy();
                }
                input.ReadMessage(ProcessStrategy);
                break;
              }
              case 26: {
                if (markingParams_ == null) {
                  MarkingParams = new global::OpenVectorFormat.MarkingParams();
                }
                input.ReadMessage(MarkingParams);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
