// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ManufacturingScenario.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ManufacturingScenarioRepository {

  /// <summary>Holder for reflection information generated from ManufacturingScenario.proto</summary>
  public static partial class ManufacturingScenarioReflection {

    #region Descriptor
    /// <summary>File descriptor for ManufacturingScenario.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ManufacturingScenarioReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtNYW51ZmFjdHVyaW5nU2NlbmFyaW8ucHJvdG8SH01hbnVmYWN0dXJpbmdT",
            "Y2VuYXJpb1JlcG9zaXRvcnkaHmJ1aWxkX3Byb2Nlc3Nvcl9zdHJhdGVneS5w",
            "cm90bxoWTW9kdWxlRGVmaW5pdGlvbi5wcm90byLeAgocTWFudWZhY3R1cmlu",
            "Z1NjZW5hcmlvRGF0YVNldBIMCgRuYW1lGAEgASgJEkkKCXNjZW5hcmlvcxgC",
            "IAMoCzI2Lk1hbnVmYWN0dXJpbmdTY2VuYXJpb1JlcG9zaXRvcnkuTWFudWZh",
            "Y3R1cmluZ1NjZW5hcmlvEkcKCmNvbnN0cmFpbnMYAyABKAsyMy5NYW51ZmFj",
            "dHVyaW5nU2NlbmFyaW9SZXBvc2l0b3J5Lk1vdmVtZW50Q29uc3RyYWlucxJX",
            "CiNnZW5lcmF0aW5nX2J1aWxkX3Byb2Nlc3Nvcl9zdHJhdGVneRgEIAEoCzIq",
            "Lm9wZW5fdmVjdG9yX2Zvcm1hdC5CdWlsZFByb2Nlc3NvclN0cmF0ZWd5EkMK",
            "EnVzZWRfbWFjaGluZV9tb2RlbBgFIAEoCzInLk1hbnVmYWN0dXJpbmdTY2Vu",
            "YXJpb1JlcG9zaXRvcnkuTW9kdWxlIt8DChVNYW51ZmFjdHVyaW5nU2NlbmFy",
            "aW8SDAoEbmFtZRgBIAEoCRJYChdwYXJ0TWFudWZhY3R1cmluZ09yZGVycxgC",
            "IAMoCzI3Lk1hbnVmYWN0dXJpbmdTY2VuYXJpb1JlcG9zaXRvcnkuUGFydE1h",
            "bnVmYWN0dXJpbmdPcmRlchJHCgpjb25zdHJhaW5zGAMgASgLMjMuTWFudWZh",
            "Y3R1cmluZ1NjZW5hcmlvUmVwb3NpdG9yeS5Nb3ZlbWVudENvbnN0cmFpbnMS",
            "VwojZ2VuZXJhdGluZ19idWlsZF9wcm9jZXNzb3Jfc3RyYXRlZ3kYBCABKAsy",
            "Ki5vcGVuX3ZlY3Rvcl9mb3JtYXQuQnVpbGRQcm9jZXNzb3JTdHJhdGVneRJJ",
            "ChZzcGVjaWZpY19tYWNoaW5lX21vZGVsGAUgASgLMicuTWFudWZhY3R1cmlu",
            "Z1NjZW5hcmlvUmVwb3NpdG9yeS5Nb2R1bGVIABJgChxvdmVycmlkZV9jdWJv",
            "aWRfYnVpbGRfdm9sdW1lGAYgASgLMjguTWFudWZhY3R1cmluZ1NjZW5hcmlv",
            "UmVwb3NpdG9yeS5DdWJvaWRCdWlsZFZvbHVtZVBhcmFtc0gAQg8KDW1hY2hp",
            "bmVfbW9kZWwiwQEKEk1vdmVtZW50Q29uc3RyYWlucxIeChZtaW5pbXVtX2Rp",
            "c3RhbmNlX2luX21tGAEgASgBEiMKG2Rpc3RhbmNlX3RvX2NvbnRhaW5lcl9p",
            "bl9tbRgCIAEoARIsCiRhbGxvd2VkX2Z1bGxfY2lyY2xlX3JvdGF0aW9uX3N0",
            "ZXBzX3oYAyABKAUSGwoTbWF4X3JvdF96X2FuZ2xlX2RlZxgEIAEoARIbChNt",
            "aW5fcm90X3pfYW5nbGVfZGVnGAUgASgBIpwDChZQYXJ0TWFudWZhY3R1cmlu",
            "Z09yZGVyEg4KBnBtb19pZBgBIAEoCRIPCgdwYXJ0X2lkGAIgASgJEhoKEnBh",
            "cnRfbnVtX3RyaWFuZ2xlcxgDIAEoBRIfChdxdWFudGl0eV90b19tYW51ZmFj",
            "dHVyZRgEIAEoBRIbChNkdWVfdGltZV9pbl9zZWNvbmRzGAUgASgDEiwKJG9y",
            "ZGVyX2NyZWF0aW9uX3RpbWVfZGVsYXlfaW5fc2Vjb25kcxgGIAEoAxIQCght",
            "YXRlcmlhbBgHIAEoCRJhCgpwcmlvcml0aWVzGAggASgLMk0uTWFudWZhY3R1",
            "cmluZ1NjZW5hcmlvUmVwb3NpdG9yeS5QYXJ0TWFudWZhY3R1cmluZ09yZGVy",
            "Lk1hbnVmYWN0dXJpbmdQcmlvcml0eRpkChVNYW51ZmFjdHVyaW5nUHJpb3Jp",
            "dHkSFgoOcHJpY2VfcHJpb3JpdHkYASABKAESGQoRZHVlX2RhdGVfcHJpb3Jp",
            "dHkYAiABKAESGAoQcXVhbGl0eV9wcmlvcml0eRgDIAEoAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::OpenVectorFormat.BuildProcessorStrategyReflection.Descriptor, global::ManufacturingScenarioRepository.ModuleDefinitionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ManufacturingScenarioRepository.ManufacturingScenarioDataSet), global::ManufacturingScenarioRepository.ManufacturingScenarioDataSet.Parser, new[]{ "Name", "Scenarios", "Constrains", "GeneratingBuildProcessorStrategy", "UsedMachineModel" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ManufacturingScenarioRepository.ManufacturingScenario), global::ManufacturingScenarioRepository.ManufacturingScenario.Parser, new[]{ "Name", "PartManufacturingOrders", "Constrains", "GeneratingBuildProcessorStrategy", "SpecificMachineModel", "OverrideCuboidBuildVolume" }, new[]{ "MachineModel" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ManufacturingScenarioRepository.MovementConstrains), global::ManufacturingScenarioRepository.MovementConstrains.Parser, new[]{ "MinimumDistanceInMm", "DistanceToContainerInMm", "AllowedFullCircleRotationStepsZ", "MaxRotZAngleDeg", "MinRotZAngleDeg" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ManufacturingScenarioRepository.PartManufacturingOrder), global::ManufacturingScenarioRepository.PartManufacturingOrder.Parser, new[]{ "PmoId", "PartId", "PartNumTriangles", "QuantityToManufacture", "DueTimeInSeconds", "OrderCreationTimeDelayInSeconds", "Material", "Priorities" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::ManufacturingScenarioRepository.PartManufacturingOrder.Types.ManufacturingPriority), global::ManufacturingScenarioRepository.PartManufacturingOrder.Types.ManufacturingPriority.Parser, new[]{ "PricePriority", "DueDatePriority", "QualityPriority" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ManufacturingScenarioDataSet : pb::IMessage<ManufacturingScenarioDataSet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ManufacturingScenarioDataSet> _parser = new pb::MessageParser<ManufacturingScenarioDataSet>(() => new ManufacturingScenarioDataSet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ManufacturingScenarioDataSet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ManufacturingScenarioRepository.ManufacturingScenarioReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ManufacturingScenarioDataSet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ManufacturingScenarioDataSet(ManufacturingScenarioDataSet other) : this() {
      name_ = other.name_;
      scenarios_ = other.scenarios_.Clone();
      constrains_ = other.constrains_ != null ? other.constrains_.Clone() : null;
      generatingBuildProcessorStrategy_ = other.generatingBuildProcessorStrategy_ != null ? other.generatingBuildProcessorStrategy_.Clone() : null;
      usedMachineModel_ = other.usedMachineModel_ != null ? other.usedMachineModel_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ManufacturingScenarioDataSet Clone() {
      return new ManufacturingScenarioDataSet(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    ///name of the data set
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "scenarios" field.</summary>
    public const int ScenariosFieldNumber = 2;
    private static readonly pb::FieldCodec<global::ManufacturingScenarioRepository.ManufacturingScenario> _repeated_scenarios_codec
        = pb::FieldCodec.ForMessage(18, global::ManufacturingScenarioRepository.ManufacturingScenario.Parser);
    private readonly pbc::RepeatedField<global::ManufacturingScenarioRepository.ManufacturingScenario> scenarios_ = new pbc::RepeatedField<global::ManufacturingScenarioRepository.ManufacturingScenario>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ManufacturingScenarioRepository.ManufacturingScenario> Scenarios {
      get { return scenarios_; }
    }

    /// <summary>Field number for the "constrains" field.</summary>
    public const int ConstrainsFieldNumber = 3;
    private global::ManufacturingScenarioRepository.MovementConstrains constrains_;
    /// <summary>
    ///global fallback movement constrains
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ManufacturingScenarioRepository.MovementConstrains Constrains {
      get { return constrains_; }
      set {
        constrains_ = value;
      }
    }

    /// <summary>Field number for the "generating_build_processor_strategy" field.</summary>
    public const int GeneratingBuildProcessorStrategyFieldNumber = 4;
    private global::OpenVectorFormat.BuildProcessorStrategy generatingBuildProcessorStrategy_;
    /// <summary>
    ///global fallback build processor strategy
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::OpenVectorFormat.BuildProcessorStrategy GeneratingBuildProcessorStrategy {
      get { return generatingBuildProcessorStrategy_; }
      set {
        generatingBuildProcessorStrategy_ = value;
      }
    }

    /// <summary>Field number for the "used_machine_model" field.</summary>
    public const int UsedMachineModelFieldNumber = 5;
    private global::ManufacturingScenarioRepository.Module usedMachineModel_;
    /// <summary>
    ///global fallback machine model
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ManufacturingScenarioRepository.Module UsedMachineModel {
      get { return usedMachineModel_; }
      set {
        usedMachineModel_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ManufacturingScenarioDataSet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ManufacturingScenarioDataSet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if(!scenarios_.Equals(other.scenarios_)) return false;
      if (!object.Equals(Constrains, other.Constrains)) return false;
      if (!object.Equals(GeneratingBuildProcessorStrategy, other.GeneratingBuildProcessorStrategy)) return false;
      if (!object.Equals(UsedMachineModel, other.UsedMachineModel)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      hash ^= scenarios_.GetHashCode();
      if (constrains_ != null) hash ^= Constrains.GetHashCode();
      if (generatingBuildProcessorStrategy_ != null) hash ^= GeneratingBuildProcessorStrategy.GetHashCode();
      if (usedMachineModel_ != null) hash ^= UsedMachineModel.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      scenarios_.WriteTo(output, _repeated_scenarios_codec);
      if (constrains_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Constrains);
      }
      if (generatingBuildProcessorStrategy_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(GeneratingBuildProcessorStrategy);
      }
      if (usedMachineModel_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(UsedMachineModel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      scenarios_.WriteTo(ref output, _repeated_scenarios_codec);
      if (constrains_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Constrains);
      }
      if (generatingBuildProcessorStrategy_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(GeneratingBuildProcessorStrategy);
      }
      if (usedMachineModel_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(UsedMachineModel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      size += scenarios_.CalculateSize(_repeated_scenarios_codec);
      if (constrains_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Constrains);
      }
      if (generatingBuildProcessorStrategy_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GeneratingBuildProcessorStrategy);
      }
      if (usedMachineModel_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UsedMachineModel);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ManufacturingScenarioDataSet other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      scenarios_.Add(other.scenarios_);
      if (other.constrains_ != null) {
        if (constrains_ == null) {
          Constrains = new global::ManufacturingScenarioRepository.MovementConstrains();
        }
        Constrains.MergeFrom(other.Constrains);
      }
      if (other.generatingBuildProcessorStrategy_ != null) {
        if (generatingBuildProcessorStrategy_ == null) {
          GeneratingBuildProcessorStrategy = new global::OpenVectorFormat.BuildProcessorStrategy();
        }
        GeneratingBuildProcessorStrategy.MergeFrom(other.GeneratingBuildProcessorStrategy);
      }
      if (other.usedMachineModel_ != null) {
        if (usedMachineModel_ == null) {
          UsedMachineModel = new global::ManufacturingScenarioRepository.Module();
        }
        UsedMachineModel.MergeFrom(other.UsedMachineModel);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            scenarios_.AddEntriesFrom(input, _repeated_scenarios_codec);
            break;
          }
          case 26: {
            if (constrains_ == null) {
              Constrains = new global::ManufacturingScenarioRepository.MovementConstrains();
            }
            input.ReadMessage(Constrains);
            break;
          }
          case 34: {
            if (generatingBuildProcessorStrategy_ == null) {
              GeneratingBuildProcessorStrategy = new global::OpenVectorFormat.BuildProcessorStrategy();
            }
            input.ReadMessage(GeneratingBuildProcessorStrategy);
            break;
          }
          case 42: {
            if (usedMachineModel_ == null) {
              UsedMachineModel = new global::ManufacturingScenarioRepository.Module();
            }
            input.ReadMessage(UsedMachineModel);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            scenarios_.AddEntriesFrom(ref input, _repeated_scenarios_codec);
            break;
          }
          case 26: {
            if (constrains_ == null) {
              Constrains = new global::ManufacturingScenarioRepository.MovementConstrains();
            }
            input.ReadMessage(Constrains);
            break;
          }
          case 34: {
            if (generatingBuildProcessorStrategy_ == null) {
              GeneratingBuildProcessorStrategy = new global::OpenVectorFormat.BuildProcessorStrategy();
            }
            input.ReadMessage(GeneratingBuildProcessorStrategy);
            break;
          }
          case 42: {
            if (usedMachineModel_ == null) {
              UsedMachineModel = new global::ManufacturingScenarioRepository.Module();
            }
            input.ReadMessage(UsedMachineModel);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ManufacturingScenario : pb::IMessage<ManufacturingScenario>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ManufacturingScenario> _parser = new pb::MessageParser<ManufacturingScenario>(() => new ManufacturingScenario());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ManufacturingScenario> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ManufacturingScenarioRepository.ManufacturingScenarioReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ManufacturingScenario() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ManufacturingScenario(ManufacturingScenario other) : this() {
      name_ = other.name_;
      partManufacturingOrders_ = other.partManufacturingOrders_.Clone();
      constrains_ = other.constrains_ != null ? other.constrains_.Clone() : null;
      generatingBuildProcessorStrategy_ = other.generatingBuildProcessorStrategy_ != null ? other.generatingBuildProcessorStrategy_.Clone() : null;
      switch (other.MachineModelCase) {
        case MachineModelOneofCase.SpecificMachineModel:
          SpecificMachineModel = other.SpecificMachineModel.Clone();
          break;
        case MachineModelOneofCase.OverrideCuboidBuildVolume:
          OverrideCuboidBuildVolume = other.OverrideCuboidBuildVolume.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ManufacturingScenario Clone() {
      return new ManufacturingScenario(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    ///human readable name of this scenario
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "partManufacturingOrders" field.</summary>
    public const int PartManufacturingOrdersFieldNumber = 2;
    private static readonly pb::FieldCodec<global::ManufacturingScenarioRepository.PartManufacturingOrder> _repeated_partManufacturingOrders_codec
        = pb::FieldCodec.ForMessage(18, global::ManufacturingScenarioRepository.PartManufacturingOrder.Parser);
    private readonly pbc::RepeatedField<global::ManufacturingScenarioRepository.PartManufacturingOrder> partManufacturingOrders_ = new pbc::RepeatedField<global::ManufacturingScenarioRepository.PartManufacturingOrder>();
    /// <summary>
    ///all part manufacturing orders that must be fulfilled to complete the scenario
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ManufacturingScenarioRepository.PartManufacturingOrder> PartManufacturingOrders {
      get { return partManufacturingOrders_; }
    }

    /// <summary>Field number for the "constrains" field.</summary>
    public const int ConstrainsFieldNumber = 3;
    private global::ManufacturingScenarioRepository.MovementConstrains constrains_;
    /// <summary>
    ///optinal movement constrains the geometries are subject to
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ManufacturingScenarioRepository.MovementConstrains Constrains {
      get { return constrains_; }
      set {
        constrains_ = value;
      }
    }

    /// <summary>Field number for the "generating_build_processor_strategy" field.</summary>
    public const int GeneratingBuildProcessorStrategyFieldNumber = 4;
    private global::OpenVectorFormat.BuildProcessorStrategy generatingBuildProcessorStrategy_;
    /// <summary>
    ///optional build processor strategy used to create the sliced part configuration (for manufacturing time prediction)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::OpenVectorFormat.BuildProcessorStrategy GeneratingBuildProcessorStrategy {
      get { return generatingBuildProcessorStrategy_; }
      set {
        generatingBuildProcessorStrategy_ = value;
      }
    }

    /// <summary>Field number for the "specific_machine_model" field.</summary>
    public const int SpecificMachineModelFieldNumber = 5;
    /// <summary>
    ///machine model used to generate the time prediction
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ManufacturingScenarioRepository.Module SpecificMachineModel {
      get { return machineModelCase_ == MachineModelOneofCase.SpecificMachineModel ? (global::ManufacturingScenarioRepository.Module) machineModel_ : null; }
      set {
        machineModel_ = value;
        machineModelCase_ = value == null ? MachineModelOneofCase.None : MachineModelOneofCase.SpecificMachineModel;
      }
    }

    /// <summary>Field number for the "override_cuboid_build_volume" field.</summary>
    public const int OverrideCuboidBuildVolumeFieldNumber = 6;
    /// <summary>
    ///cuboid buil volume to use in conjungtion with the data set fallback machine model or without a machine time calculation model
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ManufacturingScenarioRepository.CuboidBuildVolumeParams OverrideCuboidBuildVolume {
      get { return machineModelCase_ == MachineModelOneofCase.OverrideCuboidBuildVolume ? (global::ManufacturingScenarioRepository.CuboidBuildVolumeParams) machineModel_ : null; }
      set {
        machineModel_ = value;
        machineModelCase_ = value == null ? MachineModelOneofCase.None : MachineModelOneofCase.OverrideCuboidBuildVolume;
      }
    }

    private object machineModel_;
    /// <summary>Enum of possible cases for the "machine_model" oneof.</summary>
    public enum MachineModelOneofCase {
      None = 0,
      SpecificMachineModel = 5,
      OverrideCuboidBuildVolume = 6,
    }
    private MachineModelOneofCase machineModelCase_ = MachineModelOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MachineModelOneofCase MachineModelCase {
      get { return machineModelCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMachineModel() {
      machineModelCase_ = MachineModelOneofCase.None;
      machineModel_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ManufacturingScenario);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ManufacturingScenario other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if(!partManufacturingOrders_.Equals(other.partManufacturingOrders_)) return false;
      if (!object.Equals(Constrains, other.Constrains)) return false;
      if (!object.Equals(GeneratingBuildProcessorStrategy, other.GeneratingBuildProcessorStrategy)) return false;
      if (!object.Equals(SpecificMachineModel, other.SpecificMachineModel)) return false;
      if (!object.Equals(OverrideCuboidBuildVolume, other.OverrideCuboidBuildVolume)) return false;
      if (MachineModelCase != other.MachineModelCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      hash ^= partManufacturingOrders_.GetHashCode();
      if (constrains_ != null) hash ^= Constrains.GetHashCode();
      if (generatingBuildProcessorStrategy_ != null) hash ^= GeneratingBuildProcessorStrategy.GetHashCode();
      if (machineModelCase_ == MachineModelOneofCase.SpecificMachineModel) hash ^= SpecificMachineModel.GetHashCode();
      if (machineModelCase_ == MachineModelOneofCase.OverrideCuboidBuildVolume) hash ^= OverrideCuboidBuildVolume.GetHashCode();
      hash ^= (int) machineModelCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      partManufacturingOrders_.WriteTo(output, _repeated_partManufacturingOrders_codec);
      if (constrains_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Constrains);
      }
      if (generatingBuildProcessorStrategy_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(GeneratingBuildProcessorStrategy);
      }
      if (machineModelCase_ == MachineModelOneofCase.SpecificMachineModel) {
        output.WriteRawTag(42);
        output.WriteMessage(SpecificMachineModel);
      }
      if (machineModelCase_ == MachineModelOneofCase.OverrideCuboidBuildVolume) {
        output.WriteRawTag(50);
        output.WriteMessage(OverrideCuboidBuildVolume);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      partManufacturingOrders_.WriteTo(ref output, _repeated_partManufacturingOrders_codec);
      if (constrains_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Constrains);
      }
      if (generatingBuildProcessorStrategy_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(GeneratingBuildProcessorStrategy);
      }
      if (machineModelCase_ == MachineModelOneofCase.SpecificMachineModel) {
        output.WriteRawTag(42);
        output.WriteMessage(SpecificMachineModel);
      }
      if (machineModelCase_ == MachineModelOneofCase.OverrideCuboidBuildVolume) {
        output.WriteRawTag(50);
        output.WriteMessage(OverrideCuboidBuildVolume);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      size += partManufacturingOrders_.CalculateSize(_repeated_partManufacturingOrders_codec);
      if (constrains_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Constrains);
      }
      if (generatingBuildProcessorStrategy_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GeneratingBuildProcessorStrategy);
      }
      if (machineModelCase_ == MachineModelOneofCase.SpecificMachineModel) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SpecificMachineModel);
      }
      if (machineModelCase_ == MachineModelOneofCase.OverrideCuboidBuildVolume) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OverrideCuboidBuildVolume);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ManufacturingScenario other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      partManufacturingOrders_.Add(other.partManufacturingOrders_);
      if (other.constrains_ != null) {
        if (constrains_ == null) {
          Constrains = new global::ManufacturingScenarioRepository.MovementConstrains();
        }
        Constrains.MergeFrom(other.Constrains);
      }
      if (other.generatingBuildProcessorStrategy_ != null) {
        if (generatingBuildProcessorStrategy_ == null) {
          GeneratingBuildProcessorStrategy = new global::OpenVectorFormat.BuildProcessorStrategy();
        }
        GeneratingBuildProcessorStrategy.MergeFrom(other.GeneratingBuildProcessorStrategy);
      }
      switch (other.MachineModelCase) {
        case MachineModelOneofCase.SpecificMachineModel:
          if (SpecificMachineModel == null) {
            SpecificMachineModel = new global::ManufacturingScenarioRepository.Module();
          }
          SpecificMachineModel.MergeFrom(other.SpecificMachineModel);
          break;
        case MachineModelOneofCase.OverrideCuboidBuildVolume:
          if (OverrideCuboidBuildVolume == null) {
            OverrideCuboidBuildVolume = new global::ManufacturingScenarioRepository.CuboidBuildVolumeParams();
          }
          OverrideCuboidBuildVolume.MergeFrom(other.OverrideCuboidBuildVolume);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            partManufacturingOrders_.AddEntriesFrom(input, _repeated_partManufacturingOrders_codec);
            break;
          }
          case 26: {
            if (constrains_ == null) {
              Constrains = new global::ManufacturingScenarioRepository.MovementConstrains();
            }
            input.ReadMessage(Constrains);
            break;
          }
          case 34: {
            if (generatingBuildProcessorStrategy_ == null) {
              GeneratingBuildProcessorStrategy = new global::OpenVectorFormat.BuildProcessorStrategy();
            }
            input.ReadMessage(GeneratingBuildProcessorStrategy);
            break;
          }
          case 42: {
            global::ManufacturingScenarioRepository.Module subBuilder = new global::ManufacturingScenarioRepository.Module();
            if (machineModelCase_ == MachineModelOneofCase.SpecificMachineModel) {
              subBuilder.MergeFrom(SpecificMachineModel);
            }
            input.ReadMessage(subBuilder);
            SpecificMachineModel = subBuilder;
            break;
          }
          case 50: {
            global::ManufacturingScenarioRepository.CuboidBuildVolumeParams subBuilder = new global::ManufacturingScenarioRepository.CuboidBuildVolumeParams();
            if (machineModelCase_ == MachineModelOneofCase.OverrideCuboidBuildVolume) {
              subBuilder.MergeFrom(OverrideCuboidBuildVolume);
            }
            input.ReadMessage(subBuilder);
            OverrideCuboidBuildVolume = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            partManufacturingOrders_.AddEntriesFrom(ref input, _repeated_partManufacturingOrders_codec);
            break;
          }
          case 26: {
            if (constrains_ == null) {
              Constrains = new global::ManufacturingScenarioRepository.MovementConstrains();
            }
            input.ReadMessage(Constrains);
            break;
          }
          case 34: {
            if (generatingBuildProcessorStrategy_ == null) {
              GeneratingBuildProcessorStrategy = new global::OpenVectorFormat.BuildProcessorStrategy();
            }
            input.ReadMessage(GeneratingBuildProcessorStrategy);
            break;
          }
          case 42: {
            global::ManufacturingScenarioRepository.Module subBuilder = new global::ManufacturingScenarioRepository.Module();
            if (machineModelCase_ == MachineModelOneofCase.SpecificMachineModel) {
              subBuilder.MergeFrom(SpecificMachineModel);
            }
            input.ReadMessage(subBuilder);
            SpecificMachineModel = subBuilder;
            break;
          }
          case 50: {
            global::ManufacturingScenarioRepository.CuboidBuildVolumeParams subBuilder = new global::ManufacturingScenarioRepository.CuboidBuildVolumeParams();
            if (machineModelCase_ == MachineModelOneofCase.OverrideCuboidBuildVolume) {
              subBuilder.MergeFrom(OverrideCuboidBuildVolume);
            }
            input.ReadMessage(subBuilder);
            OverrideCuboidBuildVolume = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MovementConstrains : pb::IMessage<MovementConstrains>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MovementConstrains> _parser = new pb::MessageParser<MovementConstrains>(() => new MovementConstrains());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MovementConstrains> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ManufacturingScenarioRepository.ManufacturingScenarioReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MovementConstrains() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MovementConstrains(MovementConstrains other) : this() {
      minimumDistanceInMm_ = other.minimumDistanceInMm_;
      distanceToContainerInMm_ = other.distanceToContainerInMm_;
      allowedFullCircleRotationStepsZ_ = other.allowedFullCircleRotationStepsZ_;
      maxRotZAngleDeg_ = other.maxRotZAngleDeg_;
      minRotZAngleDeg_ = other.minRotZAngleDeg_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MovementConstrains Clone() {
      return new MovementConstrains(this);
    }

    /// <summary>Field number for the "minimum_distance_in_mm" field.</summary>
    public const int MinimumDistanceInMmFieldNumber = 1;
    private double minimumDistanceInMm_;
    /// <summary>
    ///the required minimum distance between nested geometries surfaces
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double MinimumDistanceInMm {
      get { return minimumDistanceInMm_; }
      set {
        minimumDistanceInMm_ = value;
      }
    }

    /// <summary>Field number for the "distance_to_container_in_mm" field.</summary>
    public const int DistanceToContainerInMmFieldNumber = 2;
    private double distanceToContainerInMm_;
    /// <summary>
    ///the minimum distance between nested parts and the container walls [mm]
    ///if not specified or smaller than minimum_distance_in_mm, minimum_distance_in_mm will be used instead
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double DistanceToContainerInMm {
      get { return distanceToContainerInMm_; }
      set {
        distanceToContainerInMm_ = value;
      }
    }

    /// <summary>Field number for the "allowed_full_circle_rotation_steps_z" field.</summary>
    public const int AllowedFullCircleRotationStepsZFieldNumber = 3;
    private int allowedFullCircleRotationStepsZ_;
    /// <summary>
    ///number of full circle rotation steps allowed
    ///the step size used is defined as 360°/allowed_full_circle_rotation_steps_z
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AllowedFullCircleRotationStepsZ {
      get { return allowedFullCircleRotationStepsZ_; }
      set {
        allowedFullCircleRotationStepsZ_ = value;
      }
    }

    /// <summary>Field number for the "max_rot_z_angle_deg" field.</summary>
    public const int MaxRotZAngleDegFieldNumber = 4;
    private double maxRotZAngleDeg_;
    /// <summary>
    ///upper limit of the allowed z rotation interval [degrees]
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double MaxRotZAngleDeg {
      get { return maxRotZAngleDeg_; }
      set {
        maxRotZAngleDeg_ = value;
      }
    }

    /// <summary>Field number for the "min_rot_z_angle_deg" field.</summary>
    public const int MinRotZAngleDegFieldNumber = 5;
    private double minRotZAngleDeg_;
    /// <summary>
    ///lower limit of the allowed z rotation interval [degrees]
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double MinRotZAngleDeg {
      get { return minRotZAngleDeg_; }
      set {
        minRotZAngleDeg_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MovementConstrains);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MovementConstrains other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(MinimumDistanceInMm, other.MinimumDistanceInMm)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DistanceToContainerInMm, other.DistanceToContainerInMm)) return false;
      if (AllowedFullCircleRotationStepsZ != other.AllowedFullCircleRotationStepsZ) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(MaxRotZAngleDeg, other.MaxRotZAngleDeg)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(MinRotZAngleDeg, other.MinRotZAngleDeg)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MinimumDistanceInMm != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(MinimumDistanceInMm);
      if (DistanceToContainerInMm != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DistanceToContainerInMm);
      if (AllowedFullCircleRotationStepsZ != 0) hash ^= AllowedFullCircleRotationStepsZ.GetHashCode();
      if (MaxRotZAngleDeg != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(MaxRotZAngleDeg);
      if (MinRotZAngleDeg != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(MinRotZAngleDeg);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MinimumDistanceInMm != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(MinimumDistanceInMm);
      }
      if (DistanceToContainerInMm != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(DistanceToContainerInMm);
      }
      if (AllowedFullCircleRotationStepsZ != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(AllowedFullCircleRotationStepsZ);
      }
      if (MaxRotZAngleDeg != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(MaxRotZAngleDeg);
      }
      if (MinRotZAngleDeg != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(MinRotZAngleDeg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MinimumDistanceInMm != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(MinimumDistanceInMm);
      }
      if (DistanceToContainerInMm != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(DistanceToContainerInMm);
      }
      if (AllowedFullCircleRotationStepsZ != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(AllowedFullCircleRotationStepsZ);
      }
      if (MaxRotZAngleDeg != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(MaxRotZAngleDeg);
      }
      if (MinRotZAngleDeg != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(MinRotZAngleDeg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MinimumDistanceInMm != 0D) {
        size += 1 + 8;
      }
      if (DistanceToContainerInMm != 0D) {
        size += 1 + 8;
      }
      if (AllowedFullCircleRotationStepsZ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AllowedFullCircleRotationStepsZ);
      }
      if (MaxRotZAngleDeg != 0D) {
        size += 1 + 8;
      }
      if (MinRotZAngleDeg != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MovementConstrains other) {
      if (other == null) {
        return;
      }
      if (other.MinimumDistanceInMm != 0D) {
        MinimumDistanceInMm = other.MinimumDistanceInMm;
      }
      if (other.DistanceToContainerInMm != 0D) {
        DistanceToContainerInMm = other.DistanceToContainerInMm;
      }
      if (other.AllowedFullCircleRotationStepsZ != 0) {
        AllowedFullCircleRotationStepsZ = other.AllowedFullCircleRotationStepsZ;
      }
      if (other.MaxRotZAngleDeg != 0D) {
        MaxRotZAngleDeg = other.MaxRotZAngleDeg;
      }
      if (other.MinRotZAngleDeg != 0D) {
        MinRotZAngleDeg = other.MinRotZAngleDeg;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            MinimumDistanceInMm = input.ReadDouble();
            break;
          }
          case 17: {
            DistanceToContainerInMm = input.ReadDouble();
            break;
          }
          case 24: {
            AllowedFullCircleRotationStepsZ = input.ReadInt32();
            break;
          }
          case 33: {
            MaxRotZAngleDeg = input.ReadDouble();
            break;
          }
          case 41: {
            MinRotZAngleDeg = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            MinimumDistanceInMm = input.ReadDouble();
            break;
          }
          case 17: {
            DistanceToContainerInMm = input.ReadDouble();
            break;
          }
          case 24: {
            AllowedFullCircleRotationStepsZ = input.ReadInt32();
            break;
          }
          case 33: {
            MaxRotZAngleDeg = input.ReadDouble();
            break;
          }
          case 41: {
            MinRotZAngleDeg = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PartManufacturingOrder : pb::IMessage<PartManufacturingOrder>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PartManufacturingOrder> _parser = new pb::MessageParser<PartManufacturingOrder>(() => new PartManufacturingOrder());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PartManufacturingOrder> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ManufacturingScenarioRepository.ManufacturingScenarioReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PartManufacturingOrder() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PartManufacturingOrder(PartManufacturingOrder other) : this() {
      pmoId_ = other.pmoId_;
      partId_ = other.partId_;
      partNumTriangles_ = other.partNumTriangles_;
      quantityToManufacture_ = other.quantityToManufacture_;
      dueTimeInSeconds_ = other.dueTimeInSeconds_;
      orderCreationTimeDelayInSeconds_ = other.orderCreationTimeDelayInSeconds_;
      material_ = other.material_;
      priorities_ = other.priorities_ != null ? other.priorities_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PartManufacturingOrder Clone() {
      return new PartManufacturingOrder(this);
    }

    /// <summary>Field number for the "pmo_id" field.</summary>
    public const int PmoIdFieldNumber = 1;
    private string pmoId_ = "";
    /// <summary>
    ///id of this pmo, will be tracked in solutions
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PmoId {
      get { return pmoId_; }
      set {
        pmoId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "part_id" field.</summary>
    public const int PartIdFieldNumber = 2;
    private string partId_ = "";
    /// <summary>
    ///id of the part to load externally
    ///parts and part configurations/orientations/supports loading is managed separatly
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PartId {
      get { return partId_; }
      set {
        partId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "part_num_triangles" field.</summary>
    public const int PartNumTrianglesFieldNumber = 3;
    private int partNumTriangles_;
    /// <summary>
    ///checksum for validation if the correct part has been loaded
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PartNumTriangles {
      get { return partNumTriangles_; }
      set {
        partNumTriangles_ = value;
      }
    }

    /// <summary>Field number for the "quantity_to_manufacture" field.</summary>
    public const int QuantityToManufactureFieldNumber = 4;
    private int quantityToManufacture_;
    /// <summary>
    ///the quantity of identical part instances needed to fulfill this PMO
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int QuantityToManufacture {
      get { return quantityToManufacture_; }
      set {
        quantityToManufacture_ = value;
      }
    }

    /// <summary>Field number for the "due_time_in_seconds" field.</summary>
    public const int DueTimeInSecondsFieldNumber = 5;
    private long dueTimeInSeconds_;
    /// <summary>
    ///time span in seconds from start of the scenario until this parts of the PMO are due for delivery
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long DueTimeInSeconds {
      get { return dueTimeInSeconds_; }
      set {
        dueTimeInSeconds_ = value;
      }
    }

    /// <summary>Field number for the "order_creation_time_delay_in_seconds" field.</summary>
    public const int OrderCreationTimeDelayInSecondsFieldNumber = 6;
    private long orderCreationTimeDelayInSeconds_;
    /// <summary>
    ///time span in seconds from start of the scenario when this PMO is created (added to the scenario/dynamic optimization)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long OrderCreationTimeDelayInSeconds {
      get { return orderCreationTimeDelayInSeconds_; }
      set {
        orderCreationTimeDelayInSeconds_ = value;
      }
    }

    /// <summary>Field number for the "material" field.</summary>
    public const int MaterialFieldNumber = 7;
    private string material_ = "";
    /// <summary>
    ///matrial of the parts
    ///for most AM processes different materials require parts to be allocated into different build jobs
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Material {
      get { return material_; }
      set {
        material_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "priorities" field.</summary>
    public const int PrioritiesFieldNumber = 8;
    private global::ManufacturingScenarioRepository.PartManufacturingOrder.Types.ManufacturingPriority priorities_;
    /// <summary>
    ///optional priorities that define the relative optimization target weightings
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ManufacturingScenarioRepository.PartManufacturingOrder.Types.ManufacturingPriority Priorities {
      get { return priorities_; }
      set {
        priorities_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PartManufacturingOrder);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PartManufacturingOrder other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PmoId != other.PmoId) return false;
      if (PartId != other.PartId) return false;
      if (PartNumTriangles != other.PartNumTriangles) return false;
      if (QuantityToManufacture != other.QuantityToManufacture) return false;
      if (DueTimeInSeconds != other.DueTimeInSeconds) return false;
      if (OrderCreationTimeDelayInSeconds != other.OrderCreationTimeDelayInSeconds) return false;
      if (Material != other.Material) return false;
      if (!object.Equals(Priorities, other.Priorities)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PmoId.Length != 0) hash ^= PmoId.GetHashCode();
      if (PartId.Length != 0) hash ^= PartId.GetHashCode();
      if (PartNumTriangles != 0) hash ^= PartNumTriangles.GetHashCode();
      if (QuantityToManufacture != 0) hash ^= QuantityToManufacture.GetHashCode();
      if (DueTimeInSeconds != 0L) hash ^= DueTimeInSeconds.GetHashCode();
      if (OrderCreationTimeDelayInSeconds != 0L) hash ^= OrderCreationTimeDelayInSeconds.GetHashCode();
      if (Material.Length != 0) hash ^= Material.GetHashCode();
      if (priorities_ != null) hash ^= Priorities.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PmoId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PmoId);
      }
      if (PartId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PartId);
      }
      if (PartNumTriangles != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PartNumTriangles);
      }
      if (QuantityToManufacture != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(QuantityToManufacture);
      }
      if (DueTimeInSeconds != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(DueTimeInSeconds);
      }
      if (OrderCreationTimeDelayInSeconds != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(OrderCreationTimeDelayInSeconds);
      }
      if (Material.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Material);
      }
      if (priorities_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Priorities);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PmoId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PmoId);
      }
      if (PartId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PartId);
      }
      if (PartNumTriangles != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PartNumTriangles);
      }
      if (QuantityToManufacture != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(QuantityToManufacture);
      }
      if (DueTimeInSeconds != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(DueTimeInSeconds);
      }
      if (OrderCreationTimeDelayInSeconds != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(OrderCreationTimeDelayInSeconds);
      }
      if (Material.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Material);
      }
      if (priorities_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Priorities);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PmoId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PmoId);
      }
      if (PartId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PartId);
      }
      if (PartNumTriangles != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PartNumTriangles);
      }
      if (QuantityToManufacture != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(QuantityToManufacture);
      }
      if (DueTimeInSeconds != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DueTimeInSeconds);
      }
      if (OrderCreationTimeDelayInSeconds != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(OrderCreationTimeDelayInSeconds);
      }
      if (Material.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Material);
      }
      if (priorities_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Priorities);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PartManufacturingOrder other) {
      if (other == null) {
        return;
      }
      if (other.PmoId.Length != 0) {
        PmoId = other.PmoId;
      }
      if (other.PartId.Length != 0) {
        PartId = other.PartId;
      }
      if (other.PartNumTriangles != 0) {
        PartNumTriangles = other.PartNumTriangles;
      }
      if (other.QuantityToManufacture != 0) {
        QuantityToManufacture = other.QuantityToManufacture;
      }
      if (other.DueTimeInSeconds != 0L) {
        DueTimeInSeconds = other.DueTimeInSeconds;
      }
      if (other.OrderCreationTimeDelayInSeconds != 0L) {
        OrderCreationTimeDelayInSeconds = other.OrderCreationTimeDelayInSeconds;
      }
      if (other.Material.Length != 0) {
        Material = other.Material;
      }
      if (other.priorities_ != null) {
        if (priorities_ == null) {
          Priorities = new global::ManufacturingScenarioRepository.PartManufacturingOrder.Types.ManufacturingPriority();
        }
        Priorities.MergeFrom(other.Priorities);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PmoId = input.ReadString();
            break;
          }
          case 18: {
            PartId = input.ReadString();
            break;
          }
          case 24: {
            PartNumTriangles = input.ReadInt32();
            break;
          }
          case 32: {
            QuantityToManufacture = input.ReadInt32();
            break;
          }
          case 40: {
            DueTimeInSeconds = input.ReadInt64();
            break;
          }
          case 48: {
            OrderCreationTimeDelayInSeconds = input.ReadInt64();
            break;
          }
          case 58: {
            Material = input.ReadString();
            break;
          }
          case 66: {
            if (priorities_ == null) {
              Priorities = new global::ManufacturingScenarioRepository.PartManufacturingOrder.Types.ManufacturingPriority();
            }
            input.ReadMessage(Priorities);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PmoId = input.ReadString();
            break;
          }
          case 18: {
            PartId = input.ReadString();
            break;
          }
          case 24: {
            PartNumTriangles = input.ReadInt32();
            break;
          }
          case 32: {
            QuantityToManufacture = input.ReadInt32();
            break;
          }
          case 40: {
            DueTimeInSeconds = input.ReadInt64();
            break;
          }
          case 48: {
            OrderCreationTimeDelayInSeconds = input.ReadInt64();
            break;
          }
          case 58: {
            Material = input.ReadString();
            break;
          }
          case 66: {
            if (priorities_ == null) {
              Priorities = new global::ManufacturingScenarioRepository.PartManufacturingOrder.Types.ManufacturingPriority();
            }
            input.ReadMessage(Priorities);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PartManufacturingOrder message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      ///specifies relative priorities of the three dimensions
      ///price, due date tardiness and quality
      ///to weight the optimization goals according to production requirements
      /// </summary>
      public sealed partial class ManufacturingPriority : pb::IMessage<ManufacturingPriority>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ManufacturingPriority> _parser = new pb::MessageParser<ManufacturingPriority>(() => new ManufacturingPriority());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ManufacturingPriority> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::ManufacturingScenarioRepository.PartManufacturingOrder.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ManufacturingPriority() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ManufacturingPriority(ManufacturingPriority other) : this() {
          pricePriority_ = other.pricePriority_;
          dueDatePriority_ = other.dueDatePriority_;
          qualityPriority_ = other.qualityPriority_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ManufacturingPriority Clone() {
          return new ManufacturingPriority(this);
        }

        /// <summary>Field number for the "price_priority" field.</summary>
        public const int PricePriorityFieldNumber = 1;
        private double pricePriority_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double PricePriority {
          get { return pricePriority_; }
          set {
            pricePriority_ = value;
          }
        }

        /// <summary>Field number for the "due_date_priority" field.</summary>
        public const int DueDatePriorityFieldNumber = 2;
        private double dueDatePriority_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double DueDatePriority {
          get { return dueDatePriority_; }
          set {
            dueDatePriority_ = value;
          }
        }

        /// <summary>Field number for the "quality_priority" field.</summary>
        public const int QualityPriorityFieldNumber = 3;
        private double qualityPriority_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double QualityPriority {
          get { return qualityPriority_; }
          set {
            qualityPriority_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as ManufacturingPriority);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ManufacturingPriority other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(PricePriority, other.PricePriority)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DueDatePriority, other.DueDatePriority)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(QualityPriority, other.QualityPriority)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (PricePriority != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(PricePriority);
          if (DueDatePriority != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DueDatePriority);
          if (QualityPriority != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(QualityPriority);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (PricePriority != 0D) {
            output.WriteRawTag(9);
            output.WriteDouble(PricePriority);
          }
          if (DueDatePriority != 0D) {
            output.WriteRawTag(17);
            output.WriteDouble(DueDatePriority);
          }
          if (QualityPriority != 0D) {
            output.WriteRawTag(25);
            output.WriteDouble(QualityPriority);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (PricePriority != 0D) {
            output.WriteRawTag(9);
            output.WriteDouble(PricePriority);
          }
          if (DueDatePriority != 0D) {
            output.WriteRawTag(17);
            output.WriteDouble(DueDatePriority);
          }
          if (QualityPriority != 0D) {
            output.WriteRawTag(25);
            output.WriteDouble(QualityPriority);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (PricePriority != 0D) {
            size += 1 + 8;
          }
          if (DueDatePriority != 0D) {
            size += 1 + 8;
          }
          if (QualityPriority != 0D) {
            size += 1 + 8;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ManufacturingPriority other) {
          if (other == null) {
            return;
          }
          if (other.PricePriority != 0D) {
            PricePriority = other.PricePriority;
          }
          if (other.DueDatePriority != 0D) {
            DueDatePriority = other.DueDatePriority;
          }
          if (other.QualityPriority != 0D) {
            QualityPriority = other.QualityPriority;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 9: {
                PricePriority = input.ReadDouble();
                break;
              }
              case 17: {
                DueDatePriority = input.ReadDouble();
                break;
              }
              case 25: {
                QualityPriority = input.ReadDouble();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 9: {
                PricePriority = input.ReadDouble();
                break;
              }
              case 17: {
                DueDatePriority = input.ReadDouble();
                break;
              }
              case 25: {
                QualityPriority = input.ReadDouble();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
